### ISSUE TITLE
Deploy app ✓ 

### ISSUE THREAD

**Issue by bkeepers** [probot/background-check#2]
@itaditya I got an instance of this repository deployed and the app is installed on this repository: https://github.com/apps/background-check. Any change that makes it into master will get automatically deployed.

What permissions do you need the GitHub App to have? Here's what is currently selected:

![image](https://user-images.githubusercontent.com/173/40525578-7c72ecca-5fa6-11e8-9299-2401d0e8a749.png)

And here are the events that it's subscribed to:

![image](https://user-images.githubusercontent.com/173/40525563-6815a8d0-5fa6-11e8-9418-908817ddf7d5.png)

**Comment by itaditya** [comment]
thanks @bkeepers

**Comment by bkeepers** [comment]
Closing since this is working now!
