### ISSUE TITLE
Set an upper limit for the number of comments analysed

### ISSUE THREAD

**Issue by itaditya** [probot/background-check#36]
Currently, we use `getUserCommentedIssues` to get 30 (due to pagination) issues as search result. Then for each issue we get 30 (again due to pagination) comments from which we filter out the user's comments. Then we run sentiment analysis on the user comments. Till we don't exhaust the toxic comments limit, the app keeps on fetching comments on issues. This must have an upper limit other wise the app will waste to much time on one user only

**Comment by bkeepers** [comment]
> …get 30 (due to pagination)…

You can pass `per_page: 100` to any API request to change the number of results. 100 is the max.

**Comment by itaditya** [comment]
actually the thing is, first I'm getting a list of issues and then I get list of comments for each issue. Now each issue has variable number of comments, and I want to analyze 100 (max) comments in total. I think here `per_page: 100` won't work
